### ISSUE TITLE
Quick start failing with ENOENT

### ISSUE THREAD

**Issue by vladikoff** [twitter-fabric/galley#22]
on OS X:
```
➜  galley-template git:(master) nvm use 4.2
Now using node v4.2.1 (npm v2.14.7)
➜  galley-template git:(master) galley run demo.dev
demo-mysql:
Error: connect ENOENT /var/run/docker.sock
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)%    
```

Looks like there a few more steps that need to be included in the quick start guide, I assume my docker vm is not running.

**Comment by phopkins** [comment]
Sounds like either your `docker-machine` either isn't running or you don't have the right environment variables in the shell to tell `docker`/`galley` how to communicate with it.

Quick start is from when you have `docker` already working locally.
