### ISSUE TITLE
Rsync issues with 1.2.0

### ISSUE THREAD

**Issue by tonybaroneee** [twitter-fabric/galley#55]
I'm a big fan of https://github.com/twitter-fabric/galley/pull/53 (nice work @samedson!), but I started to experience some issues after upgrading. First, I'm seeing a lot of rsync thrashing (made a gif to illustrate it constantly rsyncing):

![image](https://media.giphy.com/media/3oriNXK6MjSExDxD0s/giphy.gif)

Second, I experience a new crash that I've never seen before pre-1.2.0 (which may or may not be related to this PR):

![image](https://cloud.githubusercontent.com/assets/844249/20031669/85601a8c-a351-11e6-8868-7a674078f49f.png)

Anyone experiencing similar behavior?

**Comment by samedson** [comment]
@tonybaroneee Playing around with it this morning, I think the issue might be in
`ignoredFilesRegex = '/' + ignoredFilesList.join('|') + '/'`. I believe the fix is to replace that line with `ignoredFilesRegex = new RegExp(ignoredFilesList.join('|'))`. I'll try to open another pr.

**Comment by tonybaroneee** [comment]
Oh yes, totally! Regex vs. string! Good catch.

**Comment by samedson** [comment]
[56](https://github.com/twitter-fabric/galley/pull/56/files)
